name: Build binaries
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-runtime-vm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Additional dependencies
      run: |
        sudo apt-get update
        sudo apt-get install musl-tools autoconf libtool gperf -y

    - name: Clone repositories
      run: |
        /bin/bash prepare.sh

    - name: Build runtime vm
      run: |
        /bin/bash build_runtime_vm.sh

    - name: Build gvmkit-rs
      run: |
        /bin/bash build_gvmkit_rs.sh

    - name: Build self test image
      run: |
        /bin/bash build_self_test_image.sh



    - name: Compress binaries
      run: |
        tar -czf binaries.tar.gz golem/binaries

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries.tar.gz
        path: binaries.tar.gz

  build-self-test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build gvmkit-rs
        run: |
          /bin/bash build_gvmkit_rs.sh

      - name: Build self test image
        run: |
          /bin/bash build_self_test_image.sh

      - name: Compress binaries
        run: |
          tar -czf binaries_self.tar.gz golem/binaries

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries_self.tar.gz
          path: binaries_self.tar.gz

  build-yagna:
    name: Build yagna binaries (x86-64)
    env:
      RUSTFLAGS: ${{ '-C opt-level=z -C target-cpu=x86-64 -C debuginfo=1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools autoconf libtool gperf -y

      - name: Clone repositories
        run: |
          /bin/bash prepare.sh

      - name: Build all
        run: |
          /bin/bash build_yagna_debug.sh

      - name: Strip binaries
        run: |
          strip -x golem/binaries/*

      - name: Compress binaries
        run: |
          tar -czf binaries_yagna.tar.gz golem/binaries

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries_yagna.tar.gz
          path: binaries_yagna.tar.gz

  test:
    needs: [build-runtime-vm, build-yagna, build-self-test-image]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2

      - name: Download vm build
        uses: actions/download-artifact@v4
        with:
          name: binaries.tar.gz

      - name: Download yagna build
        uses: actions/download-artifact@v4
        with:
          name: binaries_yanga.tar.gz

      - name: Download self image build
        uses: actions/download-artifact@v4
        with:
          name: binaries_self.tar.gz

      - name: Extract all build files into downloaded
        run: |
          tar -xzf binaries.tar.gz
          tar -xzf binaries_yagna.tar.gz
          tar -xzf binaries_self.tar.gz
          mv golem/binaries golem/downloaded

      - name: Install binaries
        run: |
          sudo mkdir -p /usr/lib/yagna
          sudo mv golem/downloaded/plugins /usr/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/

      - name: Test binaries
        run: |
          yagna --version
          ya-provider --version
          ya-provider exe-unit list --json
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Prepare runtime
        run: |
          /bin/bash prepare_runtime.sh

      - name: Run router
        run: |
          ya-sb-router -l tcp://0.0.0.0:5555&
          sleep 1

      - name: Run requestor
        run: |
          cd golem/requestor
          yagna service run&
          sleep 3

      - name: Run provider
        run: |
          sudo chown $USER /dev/kvm 
          cd golem/provider
          golemsp setup --no-interactive
          yagna service run&
          sleep 10
          ya-provider run&
          sleep 5
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Test yagna provider payment response
        run: |
          cd golem/provider
          yagna payment status

      - name: Test yagna requestor payment response
        run: |
          cd golem/requestor
          yagna payment status

      - name: Requestor app-key list
        run: |
          cd golem/requestor
          yagna app-key list

      - name: Prepare yapapi test
        run: |
          git clone https://github.com/golemfactory/yapapi.git
          cd golem/yapapi
          poetry install
          poetry run python examples/blender/blender.py --payment-network holesky
        env:
          YAGNA_APPKEY: 66iiOdkvV29


