name: Build binaries
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Additional dependencies
      run: |
        sudo apt-get update
        sudo apt-get install musl-tools autoconf libtool gperf -y

    - name: Clone repositories
      run: |
        /bin/bash prepare.sh

    - name: Build all
      run: |
        /bin/bash build_all.sh

    - name: Compress binaries
      run: |
        tar -czf binaries.tar.gz golem/binaries

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries.tar.gz

  test:
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2

      - name: Clone repositories
        run: |
          /bin/bash prepare.sh

      - name: Download tar
        uses: actions/download-artifact@v4
        with:
          name: binaries.tar.gz

      - name: Extract into downloaded
        run: |
          mkdir golem/downloaded
          tar -xzf binaries.tar.gz -C golem/downloaded

      - name: Install binaries
        run: |
          sudo mkdir -p /usr/lib/yagna
          sudo mv golem/downloaded/plugins /usr/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/

      - name: Test binaries
        run: |
          yagna --version
          ya-provider --version
          ya-provider exe-unit list --json
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Prepare runtime
        run: |
          /bin/bash prepare_runtime.sh

      - name: Run router
        run: |
          ya-sb-router -l tcp://0.0.0.0:5555&
          sleep 1

      - name: Run requestor
        run: |
          cd golem/requestor
          yagna service run&
          sleep 10


      - name: Run provider
        run: |
          sudo chown $USER /dev/kvm 
          cd golem/provider
          golemsp setup --no-interactive
          yagna service run&
          sleep 10
          ya-provider run&
          sleep 5
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Test yagna provider payment response
        run: |
          cd golem/provider
          yagna payment status

      - name: Test yagna requestor payment response
        run: |
          cd golem/requestor
          yagna payment status

      - name: Requestor app-key list
        run: |
          cd golem/requestor
          yagna app-key list

      - name: Prepare yapapi test
        run: |
          cd golem/yapapi
          poetry install
          poetry run python examples/blender/blender.py --payment-network holesky
        env:
          YAGNA_APPKEY: 66iiOdkvV29


