name: Provision account
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: 0

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare funding
        run: |
          wget https://github.com/golemfactory/erc20_payment_lib/releases/download/pre-rel-v0.4.8-nightly/erc20_processor-linux-x86_64.tar.xz
          tar -xf erc20_processor-linux-x86_64.tar.xz
          sudo cp erc20_processor /usr/bin/erc20_processor
          erc20_processor --version

      - name: Generate ethereum accounts
        run: |
          mkdir funding && cd funding
          erc20_processor generate-key -n 5 > .env
          erc20_processor get-dev-eth
          erc20_processor mint-test-tokens
          erc20_processor run
          erc20_processor transfer --recipient 0x9939f9a566768fbc8f13744a620ea400f71f157b --token glm --all
          erc20_processor run
          erc20_processor transfer --recipient 0x9939f9a566768fbc8f13744a620ea400f71f157b --token eth --all
          erc20_processor run
          
          cat .env | grep ETH_ADDRESS_ | sed "s/#\s//g" | sed "s/:\s/=/g" >> $GITHUB_ENV
          cat .env | grep ETH_PRIVATE_KEY_ | sed "s/#\s//g" | sed "s/:\s/=/g" >> $GITHUB_ENV

      - name: Upload account
        run: |
          curl -X POST -H "Authorization: Bearer change_me" -d $ETH_PRIVATE_KEY_0 https://polygongas.org/keys/add
