name: Provision account
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  provision-account:
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: 0

    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check how many accounts are provisioned
        id: check_count # Create an ID for the step so we can refer to its output
        run: |
          COUNT=$(curl -sSL https://polygongas.org/keys/count)
          echo "Provisioned accounts count: $COUNT"
          if [ "$COUNT" -gt 100 ]; then
            echo "Too many accounts provisioned ($COUNT). Skipping remaining steps."
            echo "should_continue=false" >> $GITHUB_ENV
          else
            echo "should_continue=true" >> $GITHUB_ENV
          fi

      - name: Prepare funding
        if: env.should_continue == 'true'
        run: |
          wget https://github.com/golemfactory/erc20_payment_lib/releases/download/pre-rel-v0.4.8-nightly/erc20_processor-linux-x86_64.tar.xz
          tar -xf erc20_processor-linux-x86_64.tar.xz
          sudo cp erc20_processor /usr/bin/erc20_processor
          erc20_processor --version

      - name: Provision 10 ethereum accounts
        if: env.should_continue == 'true'
        run: |
          for i in {1..1}; do
            mkdir -p funding_$i && cd funding_$i
          
            erc20_processor generate-key -n 1 > .env
            erc20_processor get-dev-eth
            erc20_processor mint-test-tokens
            erc20_processor run
            erc20_processor transfer --recipient 0x5b984629E2Cc7570cBa7dD745b83c3dD23Ba6d0f --token glm --amount 900
            erc20_processor run
            erc20_processor balance
          
            # Extract the private key
            ETH_PRIVATE_KEY=$(cat .env | grep ETH_PRIVATE_KEY_0 | sed "s/#\s//g" | sed "s/ETH_PRIVATE_KEY_0:\s//g")
          
            # Upload the account to the server
            curl -X POST -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" -d $ETH_PRIVATE_KEY https://polygongas.org/keys/add
          
            cd ..
          done