name: Test prebuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools autoconf libtool gperf -y

      - name: Download and install binaries
        run: |
          /bin/bash download_binaries.sh
          mkdir -p ~/.local/lib/yagna
          mv golem/downloaded/plugins ~/.local/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/

      - name: Test binaries
        run: |
          yagna --version
          ya-provider --version
          ya-provider exe-unit list
      

