name: Test with assets
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      empty:
        description: 'Empty option'
        required: true
        default: 'Not used'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: 0

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare funding
        run: |
          wget https://github.com/golemfactory/erc20_payment_lib/releases/download/pre-rel-v0.4.8-nightly/erc20_processor-linux-x86_64.tar.xz
          tar -xf erc20_processor-linux-x86_64.tar.xz
          sudo cp erc20_processor /usr/bin/erc20_processor
          erc20_processor --version

      - name: Download and install binaries
        run: |
          /bin/bash download_binaries.sh

      - name: Install binaries
        run: |
          sudo mkdir -p /usr/lib/yagna
          sudo mv golem/downloaded/plugins /usr/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/ 

      - name: Prepare runtime
        run: |
          python advanced/prepare_runtime.py --mode central --payments full

      - name: Run jsexecutor example
        run: |
          cd examples/jsexecutor
          npm install
          npm run run

      - name: Run requestor
        run: |
          cd golem/requestor
          cat .env
          yagna service run&
          sleep 4
          env > yagnadir/env.log

      - name: Run provider
        run: |
          sudo chown $USER /dev/kvm 
          cd golem/provider_0
          cat .env
          golemsp setup --no-interactive
          yagna service run&
          sleep 6
          ya-provider run&
          sleep 4
          env > yagnadir/env.log
          env > providerdir/env.log
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Stop requestor
        if: always()
        run: |
          cd golem/requestor
          yagna service shutdown

      - name: Stop provider
        if: always()
        run: |
          cd golem/provider_0
          yagna service shutdown

      - name: Prepare logs
        if: always()
        run: |
          # remove image cache from upload
          rm -r golem/provider_0/providerdir/exe-unit/cache
          tar --zstd -cf data_${{ matrix.id }}.tar.zst golem/requestor/yagnadir golem/provider_0/providerdir golem/provider_0/yagnadir

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data_${{ matrix.id }}.tar.zst
          path: data_${{ matrix.id }}.tar.zst