name: Test prebuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download and install binaries
        run: |
          /bin/bash download_binaries.sh

      - name: Install binaries
        run: |
          sudo mkdir -p /usr/lib/yagna
          sudo mv golem/downloaded/plugins /usr/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/

      - name: Test binaries
        run: |
          yagna --version
          ya-provider --version
          ya-provider exe-unit list --json
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Prepare runtime
        run: |
          /bin/bash prepare_runtime.sh

      - name: Run provider
        run: |
          sudo chown $USER /dev/kvm 
          cd golem/provider
          golemsp setup --no-interactive
          yagna service run&
          sleep 10
          ya-provider run&
          sleep 5
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Run requestor
        run: |
          cd golem/requestor
          yagna service run&
          sleep 10

      - name: Test yagna response
        run: |
          cd golem/requestor
          yagna payment status
