name: Test prebuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download and install binaries
        run: |
          /bin/bash download_binaries.sh
          sudo mkdir -p /usr/lib/yagna
          sudo mv golem/downloaded/plugins /usr/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/

      - name: Test binaries
        run: |
          yagna --version
          ya-provider --version
          golemsp setup --no-interactive
          ya-provider exe-unit list --json
      

