name: Test debit notes - central local
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - timeout: 55
            interval: 15
            notes_lost: "2,3"
          - timeout: 60
            interval: 20
            notes_lost: "-1"

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2

      - name: Download and install binaries
        run: |
          /bin/bash download_binaries.sh

      - name: Install binaries
        run: |
          sudo mkdir -p /usr/lib/yagna
          sudo mv golem/downloaded/plugins /usr/lib/yagna/plugins
          sudo mv golem/downloaded/* /usr/bin/

      - name: Test binaries
        run: |
          yagna --version
          ya-provider --version
          ya-provider exe-unit list --json
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Prepare runtime
        run: |
          /bin/bash prepare_runtime.sh

      - name: Run router
        run: |
          ya-sb-router -l tcp://0.0.0.0:5555&
          sleep 1

      - name: Run requestor
        run: |
          cd golem/requestor
          cat .env
          yagna service run&

      - name: Run provider
        run: |
          sudo chown $USER /dev/kvm 
          cd golem/provider_0
          cat .env
          golemsp setup --no-interactive
          yagna service run&
          sleep 6
          ya-provider run&
          sleep 4
        env:
          YA_CONSENT_INTERNAL: "allow"
          YA_CONSENT_EXTERNAL: "allow"

      - name: Test yagna provider payment response
        run: |
          cd golem/provider_0
          yagna version show
          yagna payment status

      - name: Test yagna requestor payment response
        run: |
          yagna version show
          yagna payment status

      - name: Requestor app-key list
        run: |
          cd golem/requestor
          yagna app-key list

      - name: Run jsexecutor example
        run: |
          cd examples/debitnotetest
          npm install
          # npm run run
        env:
          DEBIT_NOTE_TIMEOUT: ${{ matrix.timeout }}
          DEBIT_NOTE_INTERVAL: ${{ matrix.interval }}
          DEBIT_NOTES_LOST: ${{ matrix.notes_lost }}

      - name: Stop requestor
        run: |
          cd golem/requestor
          yagna service shutdown

      - name: Stop provider
        run: |
          cd golem/provider_0
          yagna service shutdown

      - name: Prepare requestor logs
        run: |
          cd golem/requestor
          tar --zstd -cf ../../requestor.tar.zst yagnadir

      - name: Upload requestor logs
        uses: actions/upload-artifact@v4
        with:
          name: requestor.tar.zst
          path: requestor.tar.zst

      - name: Prepare provider logs
        run: |
          cd golem/provider_0
          tar --zstd -cf ../../provider.tar.zst providerdir yagnadir

      - name: Upload provider logs
        uses: actions/upload-artifact@v4
        with:
          name: provider.tar.zst
          path: provider.tar.zst
